#+TITLE: harp

Personal Health Record (PHR) application with focus on data privacy. This
repository keeps a /first-draft/ web version of the application. Here are a few
features of this:

1. Add journal entries, track metrics, save reports and documents, search across
   anything.
2. Search, filter, and share minimal and relevant information with your health
   care provider.
3. Data stored in plain Org mode files in local file-system. Reports and
   connected files are kept as org-attachments. This makes it easy to work with
   the records using Emacs. See ~./assets~ for an example file.
4. No syncing with any cloud store. If needed, the user will have to implement
   syncing in the safest way they deem possible.

I have stopped working on this version of the application since, except Firefox
on Linux (and Android?), every browser on every platform is a nightmare if you
think about storing data persistently forever.

The current version is running on [[https://harp-lepisma.netlify.app/]] and I use it
till I migrate to something else, though there is no documentation, poor
usability, and a lot of caveats only known to me.

I am now making a more complete version with all advanced features, including
document scanning, OCR, trends, and analytics using Kotlin Multiplatform [[https://github.com/lepisma/harp-kmp][here]].
